= Cavatina converter

This package contains a collection of scripts for parsing and translating music notation written in link:https://github.com/LexLuengas/cavatina[Cavatina]. It contains readers for rich text (.rtf) and plain text (.txt) and can translate to the MusicXML and MIDI formats.

The syntax of the Cavatina language is described on the link:http://www.cavatinafont.com/docs.html[documentation page].

== Example usages

.Convert a RTF file to MusicXML
[source]
----
$ python rtf2xml.py [path] [format]
----

.Convert a Cavatina string to MusicXML
[source]
----
$ python translator.py [string] [format]
----

== Support

Currently supported keyboard layouts are:

* English (International)
* English (US)
* English (UK, Apple)
* English (UK, Windows)
* French
* German
* Italian
* Spanish
* Spanish (ISO)
* Portuguese (Brazil, Windows)
* Portuguese (Portugal, Windows)

### Installation

Either install the library with pip via the usual `pip install cavatina`, or clone the repo and run `python setup.py install` on its root directory.

### Dependencies

*  link:https://github.com/cuthbertLab/music21[music21]

### Services

The *services* folder contains context menu shortcuts for the translator.

* _MacOS:_ run `./setup.sh` on the same folder as the workflow folders.
* _Windows:_ open and import the registry files.

### License

link:LICENSE[LGPL] © 2019 Alexis Luengas
